name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Retrieve Slack ID
        run: |
          echo "::set-output name=SLACK_ID::c234gfds"
        id: slack-id

      - name: Display ID
        run: echo "The selected color is ${{ steps.slack_id.outputs.SLACK_ID }}"
