

name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get slack ID
        id: slack-id
        run: echo '::set-output name=SLACK_ID::'$(curl "https://c106-197-90-80-162.ngrok.io")
        
      - name: Print Slack ID
        run: echo 'Slack ID ${{ fromJson(steps.slack-id.outputs.SLACK_ID).slack-handle }}'
